### ISSUE TITLE
CLLS 1.2 - UpdateAllTrackedVessels(): System.NullReferenceException

### ISSUE THREAD

**Issue by doktorstick** [mmoench/CLLS#2]
This occurs when I EVA'd from my airplane and again when I planted a flag. Edit: And when I recovered the same plane. It may be happening all the time; I only recently turned on Alt-F12, Show Exceptions.

```
[ERR 20:51:23.134] [CLLS] UpdateAllTrackedVessels(): System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.Object:get_name ()
  at CLLS.CLLS.UpdateAllTrackedVessels () [0x00000] in <filename unknown>:0 
```

**Comment by mmoench** [comment]
Hello, thank you for your report. I will take a look at this and address the issue in the next release.

**Comment by mmoench** [comment]
This should be fixed in the new release, thanks for the report.
