### ISSUE TITLE
Kerbal on separate life support after returning from EVA

### ISSUE THREAD

**Issue by doktorstick** [mmoench/CLLS#3]
I have a vessel with a command pod MK2 with one external CLLS canister. There are three Kerbals in the command pod. I EVA'd one of the Kerbals (the middle one, if that matters), and when I returned her to the command pod, I looked at the CLLS vessel stats (via the toolbar icon).

There are now two entries:
* Valentina Kerbin (orbiting Mun); Crew 1/1 Life Support: 0.98/1.00
* USK Apollo 8 (orbiting Mun): Crew 3/3 Life Support: 51.22/59.00

Valentina should be part of the USK Apollo 8 now. Hopefully I can make it back to Kerbin before she croaks.

_Edit_: Each time I EVA her and return her to the command pod a new entry appears with her name.
_Edit_: When I transitioned scenes (from space to the space center), it corrected itself, which is good. I'm not sure if Valentina would have croaked if I had fast-forwarded time for 6 hours before changing scenes.

**Comment by mmoench** [comment]
Thanks for the report. It appears that the list of tracked objects is not updated correctly when one ends an EVA. There should be not adverse effects since the EVA "vessel" does not exists anymore when the time runs out, but I will fix this in the next release.

**Comment by mmoench** [comment]
This should be fixed in the new release, thanks for the report.
